<?php

return [
    'validateTransaction' =>
    [
        'customer_name' => 'required|min:3|max:255|regex:/^[\pL\s\'\.]+$/u',
        'transaction_amount' => 'required|numeric',
        'transaction_discount' => 'required|numeric',
        'transaction_payment_type' => 'required',
        'transaction_state' => 'required',
        'transaction_code' => 'required',
        'transaction_order' => 'required|numeric',
        'organization_id' => 'required|numeric',
        'transaction_payment_type_name' => 'required',
        'transaction_cash_amount' => 'required|numeric',
        'transaction_cash_change' => 'required|numeric',
        'customer_attribute.Nama_Sales' => 'required|regex:/^[\pL\s\'\.]+$/u|min:3|max:255',
        'customer_attribute.TOP' => 'required',
        'customer_attribute.Jenis_Pelanggan' => 'required',
        'connote.connote_number' => 'required|numeric',
        'connote.connote_service' => 'required',
        'connote.connote_service_price' => 'required|numeric',
        'connote.connote_amount' => 'required|numeric',
        'connote.connote_code' => 'required',
        'connote.connote_order' => 'required|numeric',
        'connote.connote_state' => 'required',
        'connote.connote_state_id' => 'required|numeric',
        'connote.zone_code_from' => 'required',
        'connote.zone_code_to' => 'required',
        'connote.actual_weight' => 'required|numeric',
        'connote.volume_weight' => 'required|numeric',
        'connote.chargeable_weight' => 'required|numeric',
        'connote.organization_id' => 'required|numeric',
        'connote.connote_total_package' => 'required|numeric',
        'connote.connote_surcharge_amount' => 'required|numeric',
        'connote.connote_sla_day' => 'required|numeric',
        'connote.location_name' => 'required',
        'connote.location_type' => 'required',
        'connote.source_tariff_db' => 'required',
        'connote.id_source_tariff' => 'required|numeric',
        'origin_data.customer_name' => 'required|min:3|max:255|regex:/^[\pL\s\'\.]+$/u',
        'origin_data.customer_address' => 'required',
        'origin_data.customer_email' => 'required|email',
        'origin_data.customer_phone' => 'required|max:16',
        'origin_data.customer_zip_code' => 'required|numeric',
        'origin_data.zone_code' => 'required',
        'origin_data.organization_id' => 'required|numeric',
        'destination_data.customer_name' => 'required|min:3|max:255',
        'destination_data.customer_address' => 'required',
        'destination_data.customer_email' => 'email',
        'destination_data.customer_phone' => 'required|max:16',
        'destination_data.customer_zip_code' => 'required|numeric',
        'destination_data.zone_code' => 'required',
        'destination_data.organization_id' => 'required|numeric',
        'koli_data.*.koli_length' => 'required|numeric',
        'koli_data.*.awb_url' => 'required',
        'koli_data.*.koli_chargeable_weight' => 'required|numeric',
        'koli_data.*.koli_width' => 'required|numeric',
        'koli_data.*.koli_height' => 'required|numeric',
        'koli_data.*.connote_id' => 'required',
        'koli_data.*.koli_volume' => 'required|numeric',
        'koli_data.*.koli_weight' => 'required|numeric',
        'koli_data.*.koli_id' => 'required',
        'koli_data.*.koli_code' => 'required',
        'currentLocation.name' => 'required',
        'currentLocation.code' => 'required',
        'currentLocation.type' => 'required'
    ],
    'validateKoliData' =>
    [
        'koli_length' => 'required|numeric',
        'awb_url' => 'required',
        'koli_chargeable_weight' => 'required|numeric',
        'koli_width' => 'required|numeric',
        'koli_height' => 'required|numeric',
        'connote_id' => 'required',
        'koli_volume' => 'required|numeric',
        'koli_weight' => 'required|numeric',
        'koli_id' => 'required',
        'koli_code' => 'required',
    ]
];
